name: CI
env:
  VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ env.VERCEL_TOKEN }}
on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: yarn install
        run: npm install --global vercel@latest
      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=$VERCEL_TOKEN